### ISSUE TITLE
i solve this bug :(The ImageButton open or close menu bug... when you click itbug)

### ISSUE THREAD

**Issue by liufsd** [StevenRudenko/ActionsContentView#5] opened 2013-01-17 16:47 UTC
i sovle : https://github.com/StevenRudenko/ActionsContentView/issues/4#issuecomment-12367410
i'm sure that the library demo have this bug. if  you click button ..scroll view to back,,, scroll to show menu ,,  click menu ,.. again and again  like this .   it will catch a problem when you click button to show menu , you must click it  twice.....
If you don't believe me you can println your state(like "viewActionsContentView.isActionsShown()" ==true or false ??)...
so  i think you can use your anothen method:viewActionsContentView.toggleActions() to show or close menu .  and  you must create another boolean state to records your menu state (open or  close )whatever you scroll or click ..
here is my code:
/**
- menu state open or close content show --false content hid --true
  - */
    private boolean mMenuOpenstate = false;
    .........................................
    public void toggleActions() {
    Log.e(TAG, "" + mMenuOpenstate);
    if (mMenuOpenstate) {
        showContent();
        mMenuOpenstate=false;
    }else {
    
    ```
    showActions();
    mMenuOpenstate=true;
    ```
    
    }
    }
    .......................................................
    /**
    - Starts auto-scrolling to bound which is closer to current position.
      */
      private void completeScrolling() {
      final int startX = viewContentContainer.getScrollX();
      
      final int rightBound = getRightBound();
      final int middle = -rightBound / 2;
      if (startX > middle) {
      
      ```
      mMenuOpenstate = false;
      Log.e(TAG, "show" + "mMenuOpenstate " + mMenuOpenstate);
      showContent(mFlingDuration);
      ```
      
      } else {
      
      ```
      mMenuOpenstate = true;
      Log.e(TAG, "hid" + "mMenuOpenstate " + mMenuOpenstate);
      hideContent(mFlingDuration);
      ```
      
      }
      }
      .............................................................
      i wish it can help you  to  solve this problem even a small problem..........

**Comment by StevenRudenko** [comment] 2013-01-17 17:18
I saw your comments for ticket #4 which sounds same as this one. Will apply fix tomorrow. Thanks for you help.

Closing this as far it is duplicate of #4 .

**Closed as completed by StevenRudenko** 2013-01-17 17:18 UTC
Labels: duplicate
